name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - master # Trigger the workflow on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # The runner will use the latest Ubuntu image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # This checks out the code from your GitHub repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: happiness000
          password: lhg20020109

      - name: Build Docker image
        run: |
          docker build -t happiness000/githubscraping:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push happiness000/githubscraping:latest

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Install Docker on remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem bwang@142.93.193.118 << 'EOF'
            # Update and install dependencies
            echo "chica123" | sudo -S apt-get update
            echo "chica123" | sudo -S apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            echo "chica123" | sudo -S curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo -S apt-key add -
            echo "chica123" | sudo -S add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            echo "chica123" | sudo -S apt-get update
            echo "chica123" | sudo -S apt-get install -y docker-ce
            echo "chica123" | sudo -S systemctl start docker
            echo "chica123" | sudo -S systemctl enable docker
            # Add the user to the Docker group to avoid sudo for Docker commands
            echo "chica123" | sudo -S usermod -aG docker bwang
          EOF

      - name: Restart server to apply Docker group changes
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem bwang@142.93.193.118 << 'EOF'
            echo "chica123" | sudo -S reboot
          EOF

      - name: Deploy to remote server
        run: |
          # Wait for the server to reboot and reconnect
          sleep 60
          ssh -o StrictHostKeyChecking=no -i private_key.pem bwang@142.93.193.118 << 'EOF'
            # Pull and run the Docker image
            echo "chica123" | sudo -S docker pull happiness000/githubscraping:latest
            echo "chica123" | sudo -S docker run -d -p 5000:5000 happiness000/githubscraping:latest
          EOF
