name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - master # Trigger the workflow on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest # The runner will use the latest Ubuntu image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # This checks out the code from your GitHub repository

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: happiness000
          password: lhg20020109

      - name: Build Docker image
        run: |
          docker build -t happiness000/githubscraping:latest .

      - name: Push Docker image to Docker Hub
        run: |
          docker push happiness000/githubscraping:latest

      - name: Install Docker on remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} bwang@142.93.193.118 << 'EOF'
            # Update and install dependencies
            sudo apt-get update
            sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
            # Add Docker’s official GPG key
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
            # Add Docker repository
            sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            sudo apt-get update
            # Install Docker
            sudo apt-get install -y docker-ce
            sudo systemctl start docker
            sudo systemctl enable docker
          EOF

      - name: Deploy to remote server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} bwang@142.93.193.118 'docker pull happiness000/githubscraping:latest && docker run -d -p 5000:5000 happiness000/githubscraping:latest'
